name: baby_assistant
description: "Baby AI Assistant"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_overlay_window: ^0.4.5
  permission_handler: ^11.3.1
  speech_to_text: ^6.6.1
  flutter_tts: ^4.1.0
  http: ^1.2.1
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
